### ISSUE TITLE
InfluxQL division by floating point bugs

### ISSUE THREAD

**Issue by fmgonsalves** [ovh/erlenmeyer#40]
Hi all,

I'm doing some tests using the InfluxQL protocol and I seem to run into a problem doing some basic math on fields. I'm not sure if this has already been discussed before but here goes.

Query that works: `SELECT mean("11964") * 100 / 16 FROM "fgs" WHERE time >= 1581436723284ms and time <= 1581570861545ms GROUP BY time(2m) fill(null)`

Query that doesn't work: `SELECT mean("11964") * 100 / 1.6 FROM "fgs" WHERE time >= 1581436723284ms and time <= 1581570861545ms GROUP BY time(2m) fill(null)`

Error received: _ERR: Invalid generated query: returned error is - Exception at 'DUP 'tags' STORE=>PARTITION<=' in section [TOP] (Empty stack.)_

The only difference between the queries is division by an integer in the first one and a floating point number in the second one.
I am also facing similar problems when trying to divide two fields by name, eg. `SELECT mean("ABC") / mean("XYZ")...`

Any idea where this is coming from?

**Comment by fmgonsalves** [comment]
Hi,

Is there any update on this issue?

**Comment by aurrelhebert** [comment]
Hi @fmgonsalves indeed float number where not interpreted with InfluxQL as not parsed in expression. It should be better now

**Comment by fmgonsalves** [comment]
Hi,

Apparently I am now able to make requests such as `SELECT mean("abc") / mean("XYZ")`

However, dividing by floating points still seems to not work.

Working: `SELECT mean("11964") / 1 AS "metrics_math_decimal" FROM "fgs" WHERE time >= 1580521652940ms and time <= 1580524378692ms GROUP BY time(2s) fill(null)`

Not working: `SELECT mean("11964") / 1.0 AS "metrics_math_decimal" FROM "fgs" WHERE time >= 1580521652940ms and time <= 1580524378692ms GROUP BY time(2s) fill(null)`
