### ISSUE TITLE
Brackets causing problem on OVH

### ISSUE THREAD

**Issue by GuillaumeDrillaud** [ovh/erlenmeyer#46]
When pushing data to influxdb on OVH we encounter a problem when field names contain brackets (ie: [ and ]).
This problem doesn't exist when pushing to an instance of influxdb running locally.
Which made us think the problem came from OVH.

The problem is that no data is saved on metrics/no data can be visualized on Grafana.
Here is a query example  : 
```
'<measurement>,name=<name> example[]=11.4 1602374430', 
'<measurement>,name=<name> example[]=11.3 1602374460'
```
Once this request is sent, we can see the measurement and the field name in Grafana but no data are displayed.

**Comment by aurrelhebert** [comment]
Hello @GuillaumeDrillaud, did you try to URL encode your fields? Instead of [] could you try with %5B%5D?

**Comment by GuillaumeDrillaud** [comment]
Hi @aurrelhebert, I've tried your solution, but it doesn't work because my points are in the body of the request.
So it's understood by metrics as text, which gives this result in the field name on Grafana : example %5B%5D.

**Comment by aurrelhebert** [comment]
Hi @GuillaumeDrillaud  I test a Vanilla Influx push with bracket inside field name and its working fine: 
curl --request POST \
--url https://metrics:TOKEN@127.0.0.1:9100/influxdb/write \
--data 'series_name,field=test[]test,other=test2 value=42 1605173315000000'
I will close this issues, as it seems to work fine, and it's not related to erlenmeyer. The project related to write is https://github.com/ovh/catalyst/
